FROM node:alpine

WORKDIR /usr/app

COPY package.json .

RUN npm install

# We can ignore this if we are directly mounting the working directory into the docker images.
COPY ./ ./ 

CMD ["npm", "run", "start"]